{"dept_url": "https://www.uidaho.edu/cbe/degrees/accounting"}
{"dept_url": "https://www.uidaho.edu/cbe/degrees/master-of-accountancy"}
{"dept_url": "https://www.uidaho.edu/class/csj/academics/graduate/anthropology"}
{"dept_url": "https://www.uidaho.edu/caa/programs/art-design/undergraduate-program/baart"}
{"dept_url": "https://www.uidaho.edu/cals/animal-veterinary-and-food-sciences/ms-avs"}
{"dept_url": "https://www.uidaho.edu/class/csj/academics/undergrad/anthropology"}
{"dept_url": "https://www.uidaho.edu/degree-finder/animal-and-veterinary-science/bs-animal-and-vet-science"}
{"dept_url": "https://www.uidaho.edu/ed/mvsc/academics/at/msat"}
{"dept_url": "https://www.uidaho.edu/cals/agricultural-education-leadership-and-communications/bs-ascl"}
{"dept_url": "https://www.uidaho.edu/cals/animal-veterinary-and-food-sciences/phd-animal-physiology"}
{"dept_url": "https://www.uidaho.edu/cals/soil-and-water-systems/bs-water-science-and-management"}
{"dept_url": "https://www.uidaho.edu/cals/soil-and-water-systems/bs-ag-systems-management"}
{"dept_url": "https://www.uidaho.edu/caa/programs/architecture/m-architecture"}
{"dept_url": "https://www.uidaho.edu/cnr/undergraduate-majors/bs-wildlife"}
{"dept_url": "https://www.uidaho.edu/cals/agricultural-economics-and-rural-sociology/ms-applied-economics"}
{"dept_url": "https://www.uidaho.edu/law/juris-doctor"}
{"dept_url": "https://www.uidaho.edu/cals/family-and-consumer-sciences/bs-apparel-textiles-and-design"}
{"dept_url": "https://www.uidaho.edu/cals/majors-and-degrees/ms-phd-water-resources"}
{"dept_url": "https://www.uidaho.edu/ed/mvsc/academics/at/dat"}
{"dept_url": "https://www.uidaho.edu/caa/programs/virtual-technology-and-design/bs-virtual-technology-and-design"}
{"dept_url": "https://www.uidaho.edu/cals/majors-and-degrees/ms-phd-water-resources"}
{"dept_url": "https://www.uidaho.edu/engr/departments/neim/degrees/technology-management"}
{"dept_url": "https://www.uidaho.edu/law/juris-doctor"}
{"dept_url": "https://www.uidaho.edu/caa/programs/art-design/undergraduate-program/bfa-art-and-design"}
{"dept_url": "https://www.uidaho.edu/sci/mathstat/bs-stats"}
{"dept_url": "https://www.uidaho.edu/cals/soil-and-water-systems/bs-sustainable-food-systems"}
{"dept_url": "https://www.uidaho.edu/sci/mathstat/ms-stats"}
{"dept_url": "https://www.uidaho.edu/caa/programs/architecture/bs-architecture"}
{"dept_url": "https://www.uidaho.edu/caa/programs/art-design/mfa-art"}
{"dept_url": "https://www.uidaho.edu/cals/soil-and-water-systems/ms-soil-and-land-resources"}
{"dept_url": "https://www.uidaho.edu/cals/soil-and-water-systems/ms-soil-and-land-resources"}
{"dept_url": "https://www.uidaho.edu/class/csj/academics/undergrad/sociology"}
{"dept_url": "https://www.uidaho.edu/class/theatre/academics/master-of-fine-arts"}
{"dept_url": "https://www.uidaho.edu/ed/mvsc/academics/recreation/recreation-bs"}
{"dept_url": "https://www.uidaho.edu/class/politics-and-philosophy/academics/public-administration"}
{"dept_url": "https://www.uidaho.edu/class/jamm/degrees/public-relations"}
{"dept_url": "https://www.uidaho.edu/class/psychcomm/graduate/ms-in-human-factors"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-health-programs/pre-public-health"}
{"dept_url": "https://www.uidaho.edu/cnr/undergraduate-majors/bs-rangeland-conservation"}
{"dept_url": "https://www.uidaho.edu/class/theatre/academics/ba-bs-theatre"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-health-programs/pre-physical-therapy"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-health-programs/pre-pharmacy"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-health-programs/pre-optometry"}
{"dept_url": "https://www.uidaho.edu/class/psychcomm/undergraduate/psychology"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-health-programs/pre-occupational-therapy"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-health-programs/pre-physician-assistant"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-med/pre-medical-technologist"}
{"dept_url": "https://www.uidaho.edu/ed/ci/academics/secondary-ed/sec-ed-bs"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-health-programs/pre-dietetics"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-health-programs/pre-athletic-training"}
{"dept_url": "https://www.uidaho.edu/ed/ci/academics/special-ed/sp-ed-med"}
{"dept_url": "https://www.uidaho.edu/class/politics-and-philosophy/academics/politics/phd"}
{"dept_url": "https://www.uidaho.edu/class/theatre/academics/bfa-theatre"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-med"}
{"dept_url": "https://www.uidaho.edu/cals/plant-sciences/ms-plant-sci"}
{"dept_url": "https://www.uidaho.edu/class/mlc/majors/spanish"}
{"dept_url": "https://www.uidaho.edu/cals/plant-sciences/ms-plant-sci"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-health-programs/pre-applied-psychology"}
{"dept_url": "https://www.uidaho.edu/sci/physics/ms-physics"}
{"dept_url": "https://www.uidaho.edu/sci/physics/bs-physics"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-health-programs/pre-nursing"}
{"dept_url": "https://www.uidaho.edu/ed/mvsc/academics/pete/pete-med"}
{"dept_url": "https://www.uidaho.edu/class/interdisciplinary/organizational-sciences"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-health-programs/pre-chiropractic"}
{"dept_url": "https://www.uidaho.edu/cals/entomology-plant-pathology-and-nematology/ms-plant-pathology"}
{"dept_url": "https://www.uidaho.edu/sci/physics/phd-physics"}
{"dept_url": "https://www.uidaho.edu/engr/phd-nuclear-engr"}
{"dept_url": "https://www.uidaho.edu/engr/ms-nuclear-engr"}
{"dept_url": "https://www.uidaho.edu/engr/mengr-nuclear-engr"}
{"dept_url": "https://www.uidaho.edu/sci/biology/phd-neuroscience"}
{"dept_url": "https://www.uidaho.edu/sci/biology/ms-neuroscience"}
{"dept_url": "https://www.uidaho.edu/cnr/grad-programs/on-campus-degrees/master-of-natural-resources"}
{"dept_url": "https://www.uidaho.edu/cnr/grad-programs/on-campus-degrees/master-of-natural-resources"}
{"dept_url": "https://www.uidaho.edu/class/politics-and-philosophy/academics/politics/ma"}
{"dept_url": "https://www.uidaho.edu/cnr/grad-programs/on-campus-degrees/master-of-natural-resources"}
{"dept_url": "https://www.uidaho.edu/cnr/grad-programs/on-campus-degrees/natural-resources"}
{"dept_url": "https://www.uidaho.edu/cals/family-and-consumer-sciences/bs-nutritional-sciences"}
{"dept_url": "https://www.uidaho.edu/class/music/degrees/graduate/ma-music"}
{"dept_url": "https://www.uidaho.edu/class/music/degrees/graduate/master-of-music"}
{"dept_url": "https://www.uidaho.edu/class/politics-and-philosophy/academics/politics/ba-bs"}
{"dept_url": "https://www.uidaho.edu/cnr/grad-programs/on-campus-degrees/master-of-natural-resources"}
{"dept_url": "https://www.uidaho.edu/class/politics-and-philosophy/academics/philosophy/ba-bs"}
{"dept_url": "https://www.uidaho.edu/class/music/b-mus-music"}
{"dept_url": "https://www.uidaho.edu/sci/biology/bs-mbb"}
{"dept_url": "https://www.uidaho.edu/class/mlc/majors/modern-language-business"}
{"dept_url": "https://www.uidaho.edu/sci/biology/phd-mmbb"}
{"dept_url": "https://www.uidaho.edu/current-students/academic-support/academic-advising/pre-health-advising/pre-health-programs/pre-dentistry"}
{"dept_url": "https://www.uidaho.edu/sci/biology/bs-medical-science"}
{"dept_url": "https://www.uidaho.edu/engr/departments/me/phd-mech-engr"}
{"dept_url": "https://www.uidaho.edu/engr/departments/me/ms-mech-engr"}
{"dept_url": "https://www.uidaho.edu/cnr/undergraduate-majors/bs-nrc"}
{"dept_url": "https://www.uidaho.edu/engr/departments/me/bs-mech-engr"}
{"dept_url": "https://www.uidaho.edu/sci/biology/bs-microbio"}
{"dept_url": "https://www.uidaho.edu/sci/mathstat/mat-math"}
{"dept_url": "https://www.uidaho.edu/sci/mathstat/ms-math"}
{"dept_url": "https://www.uidaho.edu/sci/mathstat/bs-math"}
{"dept_url": "https://www.uidaho.edu/cbe/degrees/marketing"}
{"dept_url": "https://www.uidaho.edu/cbe/degrees/management-information-systems"}
{"dept_url": "https://www.uidaho.edu/cbe/degrees/operations-management"}
{"dept_url": "https://www.uidaho.edu/sci/mathstat/phd-math"}
{"dept_url": "https://www.uidaho.edu/caa/programs/landscape-architecture/academic-programs/graduate/mla-landscape-architecture"}
{"dept_url": "https://www.uidaho.edu/caa/programs/landscape-architecture/academic-programs/bsla/bs-landscape-architecture"}
{"dept_url": "https://www.uidaho.edu/law/juris-doctor"}
{"dept_url": "https://www.uidaho.edu/ed/mvsc/academics/esh/mls-ms-esh"}
{"dept_url": "https://www.uidaho.edu/class/international-studies/academics"}
{"dept_url": "https://www.uidaho.edu/caa/programs/interior-architecture-and-design/b-interior-arch-design"}
{"dept_url": "https://www.uidaho.edu/cogs/programs-offered/interdisciplinary-studies"}
{"dept_url": "https://www.uidaho.edu/caa/programs/architecture/ms-integrated-architecture-design"}
{"dept_url": "https://www.uidaho.edu/class/interdisciplinary/interdisciplinary-studies"}
{"dept_url": "https://www.uidaho.edu/cnr/grad-programs/on-campus-degrees/natural-resources-phd"}
{"dept_url": "https://www.uidaho.edu/class/jamm/degrees/journalism"}
{"dept_url": "https://www.uidaho.edu/class/history/academics/graduate/phd"}
{"dept_url": "https://www.uidaho.edu/cals/plant-sciences/bs-horticulture-and-urban-agriculture"}
{"dept_url": "https://www.uidaho.edu/class/history/academics/graduate/ma"}
{"dept_url": "https://www.uidaho.edu/engr/departments/me/mengr-mech-engr"}
{"dept_url": "https://www.uidaho.edu/cals/entomology-plant-pathology-and-nematology/bs-global-disease-ecology"}
{"dept_url": "https://www.uidaho.edu/sci/geo/phd-geology"}
{"dept_url": "https://www.uidaho.edu/cbe/degrees/management-and-human-resources"}
{"dept_url": "https://www.uidaho.edu/sci/geo/bs-geology"}
{"dept_url": "https://www.uidaho.edu/class/music/ba-bs-music"}
{"dept_url": "https://www.uidaho.edu/engr/departments/cee/ms-geo-engr"}
{"dept_url": "https://www.uidaho.edu/class/history/academics/undergraduate"}
{"dept_url": "https://www.uidaho.edu/sci/geo/bs-geography"}
{"dept_url": "https://www.uidaho.edu/class/generalstudies/students"}
{"dept_url": "https://www.uidaho.edu/sci/geo/ms-geology"}
{"dept_url": "https://www.uidaho.edu/cnr/undergraduate-majors/bs-forestry"}
{"dept_url": "https://www.uidaho.edu/cals/animal-veterinary-and-food-sciences/phd-food-science"}
{"dept_url": "https://www.uidaho.edu/degree-finder/geography/ms-geography"}
{"dept_url": "https://www.uidaho.edu/cals/animal-veterinary-and-food-sciences/ms-food-science"}
{"dept_url": "https://www.uidaho.edu/cals/animal-veterinary-and-food-sciences/bs-food-science"}
{"dept_url": "https://www.uidaho.edu/cals/family-and-consumer-sciences/bs-food-and-nutrition"}
{"dept_url": "https://www.uidaho.edu/class/mlc/majors/french"}
{"dept_url": "https://www.uidaho.edu/cnr/undergraduate-majors/bs-fisheries"}
{"dept_url": "https://www.uidaho.edu/cbe/degrees/finance"}
{"dept_url": "https://www.uidaho.edu/cnr/undergraduate-majors/forest-and-sustainable-products"}
{"dept_url": "https://www.uidaho.edu/class/mlc/majors/latin-american-studies"}
{"dept_url": "https://www.uidaho.edu/cnr/undergraduate-majors/bs-fire-ecology"}
{"dept_url": "https://www.uidaho.edu/ed/mvsc/academics/esh/esh-bs"}
{"dept_url": "https://www.uidaho.edu/cals/family-and-consumer-sciences/bs-human-development-and-family-studies"}
{"dept_url": "https://www.uidaho.edu/class/interdisciplinary/film-tv"}
{"dept_url": "https://www.uidaho.edu/cals/soil-and-water-systems/bs-environmental-soil-science"}
{"dept_url": "https://www.uidaho.edu/cnr/grad-programs/on-campus-degrees/environmental-science"}
{"dept_url": "https://www.uidaho.edu/cals/family-and-consumer-sciences/bs-family-and-consumer-sciences"}
{"dept_url": "https://www.uidaho.edu/cnr/undergraduate-majors/bs-envs"}
{"dept_url": "https://www.uidaho.edu/cals/entomology-plant-pathology-and-nematology/ms-entomology"}
{"dept_url": "https://www.uidaho.edu/cals/entomology-plant-pathology-and-nematology/ms-entomology"}
{"dept_url": "https://www.uidaho.edu/cals/entomology-plant-pathology-and-nematology/bs-entomology"}
{"dept_url": "https://www.uidaho.edu/class/psychcomm/graduate/phd-in-human-factors"}
{"dept_url": "https://www.uidaho.edu/engr/bs-indust-tech"}
{"dept_url": "https://www.uidaho.edu/engr/departments/neim/degrees/engineering-management"}
{"dept_url": "https://www.uidaho.edu/cnr/grad-programs/on-campus-degrees/environmental-science-phd"}
{"dept_url": "https://www.uidaho.edu/engr/departments/ece/ms-electrical-engr"}
{"dept_url": "https://www.uidaho.edu/degree-finder/geography/phd-geography"}
{"dept_url": "https://www.uidaho.edu/engr/departments/ece/mengr-electrical-engr"}
{"dept_url": "https://www.uidaho.edu/class/english/academics/undergrad"}
{"dept_url": "https://www.uidaho.edu/ed/lc/academics/ed-leadership/ed-leadership-med"}
{"dept_url": "https://www.uidaho.edu/ed/lc/academics/ed-leadership/ed-leadership-eds"}
{"dept_url": "https://www.uidaho.edu/ed/ci/academics/elementary-ed/elem-ed-bs"}
{"dept_url": "https://www.uidaho.edu/ed/academics/doctoral-degrees"}
{"dept_url": "https://www.uidaho.edu/cnr/undergraduate-majors/bs-ecb"}
{"dept_url": "https://www.uidaho.edu/cals/family-and-consumer-sciences/ms-fcs"}
{"dept_url": "https://www.uidaho.edu/cals/family-and-consumer-sciences/bs-early-childhood-education"}
{"dept_url": "https://www.uidaho.edu/class/english/academics/graduate/ma-english"}
{"dept_url": "https://www.uidaho.edu/engr/departments/cs/degrees/bs-cybersecurity"}
{"dept_url": "https://www.uidaho.edu/engr/departments/ece/phd-electrical-engr"}
{"dept_url": "https://www.uidaho.edu/cnr/grad-programs/on-campus-degrees/jd-ms"}
{"dept_url": "https://www.uidaho.edu/ed/ci/academics/ci/ci-med"}
{"dept_url": "https://www.uidaho.edu/ed/mvsc/academics/dance/dance-bs"}
{"dept_url": "https://www.uidaho.edu/degree-finder/crop-management/bs-crop-science"}
{"dept_url": "https://www.uidaho.edu/class/csj/academics/undergrad/criminology"}
{"dept_url": "https://www.uidaho.edu/class/english/academics/graduate/mfa-creative-writing/about"}
{"dept_url": "https://www.uidaho.edu/engr/departments/cs/phd-computer-science"}
{"dept_url": "https://www.uidaho.edu/ed/ci/academics/ci/ci-eds"}
{"dept_url": "https://www.uidaho.edu/engr/departments/ece/ms-computer-engr"}
{"dept_url": "https://www.uidaho.edu/engr/departments/ece/mengr-computer-engr"}
{"dept_url": "https://www.uidaho.edu/engr/departments/ece/bs-computer-engr"}
{"dept_url": "https://www.uidaho.edu/engr/departments/cs/bs-computer-science"}
{"dept_url": "https://www.uidaho.edu/ed/academics/doctoral-degrees"}
{"dept_url": "https://www.uidaho.edu/engr/departments/cee/phd-civil-engr"}
{"dept_url": "https://www.uidaho.edu/class/interdisciplinary/economics"}
{"dept_url": "https://www.uidaho.edu/engr/departments/cee/ms-civil-engr"}
{"dept_url": "https://www.uidaho.edu/engr/departments/cee/mengr-civil-engr"}
{"dept_url": "https://www.uidaho.edu/cals/family-and-consumer-sciences/bs-child-development"}
{"dept_url": "https://www.uidaho.edu/sci/chem/ms-chemistry"}
{"dept_url": "https://www.uidaho.edu/class/psychcomm/undergraduate/communication"}
{"dept_url": "https://www.uidaho.edu/engr/departments/chbe/degrees/cheme/phd"}
{"dept_url": "https://www.uidaho.edu/engr/departments/cs/ms-computer-science"}
{"dept_url": "https://www.uidaho.edu/engr/departments/chbe/degrees/cheme/ms"}
{"dept_url": "https://www.uidaho.edu/sci/chem/phd-chemistry"}
{"dept_url": "https://www.uidaho.edu/engr/departments/chbe/degrees/cheme/bs"}
{"dept_url": "https://www.uidaho.edu/cals/plant-sciences/bs-crop-science"}
{"dept_url": "https://www.uidaho.edu/ed/ci/academics/cte/cte-bs"}
{"dept_url": "https://www.uidaho.edu/cbe/degrees/business-economics"}
{"dept_url": "https://www.uidaho.edu/sci/chem/bs-chemistry"}
{"dept_url": "https://www.uidaho.edu/sci/biology/ms-biology"}
{"dept_url": "https://www.uidaho.edu/engr/departments/chbe/degrees/cheme/mengr"}
{"dept_url": "https://www.uidaho.edu/engr/departments/chbe/degrees/be/phd"}
{"dept_url": "https://www.uidaho.edu/sci/biology/phd-biology"}
{"dept_url": "https://www.uidaho.edu/engr/departments/chbe/degrees/be/mengr"}
{"dept_url": "https://www.uidaho.edu/sci/biology/ba-biology"}
{"dept_url": "https://www.uidaho.edu/engr/departments/chbe/degrees/be/ms"}
{"dept_url": "https://www.uidaho.edu/sci/bcb/ms-bioinformatics"}
{"dept_url": "https://www.uidaho.edu/class/jamm/degrees/broadcasting-digital-media"}
{"dept_url": "https://www.uidaho.edu/sci/biology/bs-biochemistry"}
{"dept_url": "https://www.uidaho.edu/cals/plant-sciences/bs-biotechnology-and-plant-genomics"}
{"dept_url": "https://www.uidaho.edu/cals/agricultural-economics-and-rural-sociology/majors-and-degrees"}
{"dept_url": "https://www.uidaho.edu/engr/departments/cee/degrees/bs"}
{"dept_url": "https://www.uidaho.edu/engr/departments/chbe/degrees/be/bs"}
{"dept_url": "https://www.uidaho.edu/class/jamm/degrees/advertising"}
{"dept_url": "https://www.uidaho.edu/ed/lc/academics/aoll/aoll-ms"}
{"dept_url": "https://www.uidaho.edu/cals/agricultural-education-leadership-and-communications/ms-ag-ed"}
{"dept_url": "https://www.uidaho.edu/sci/bcb/phd-bioinformatics"}
{"dept_url": "https://www.uidaho.edu/engr/departments/ece/bs-electrical-engr"}
{"dept_url": "https://www.uidaho.edu/cals/agricultural-education-leadership-and-communications/bs-ag-ed"}
{"dept_url": "https://www.uidaho.edu/cals/family-and-consumer-sciences/ms-dietetics"}
{"dept_url": "https://www.uidaho.edu/cbe/degrees/master-of-accountancy"}
