{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://www.gsd.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "http://mmscimmunology.hms.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://gsas.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://www.extension.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://www.seas.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://extension.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://www.hbs.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://www.gse.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://harvardms.mba"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://www.hsph.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://www.hks.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://www.harvardonline.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://postgraduateeducation.hms.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://hsdm.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://anthropology.fas.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://www.hms.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "http://informaticstraining.hms.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://hls.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://mde.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://hds.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://ghsm.hms.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://www.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://bioethics.hms.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "https://meded.hms.harvard.edu"}
{"name": "Harvard_University", "department": "", "scraped_date": "2022-05-14", "link": "http://eas.fas.harvard.edu"}
